SET SQL_SAFE_UPDATES = 0;

delete from cities;
delete from users;
delete from genders;

ALTER TABLE cities ADD CONSTRAINT city_name_uq UNIQUE (city_name);

insert into cities values 
(null, 'Айтос           '),
(null, 'Асеновград      '),
(null, 'Ахтопол         '),
(null, 'Балчик          '),
(null, 'Банкя           '),
(null, 'Банско          '),
(null, 'Батак           '),
(null, 'Белене          '),
(null, 'Белица          '),
(null, 'Белослав        '),
(null, 'Берковица       '),
(null, 'Битоля          '),
(null, 'Благоевград     '),
(null, 'Ботевград       '),
(null, 'Брацигово       '),
(null, 'Брезник         '),
(null, 'Бургас          '),
(null, 'Бяла            '),
(null, 'Варна           '),
(null, 'Велес           '),
(null, 'Велики Преслав  '),
(null, 'Велико Търново  '),
(null, 'Велинград       '),
(null, 'Видин           '),
(null, 'Враца           '),
(null, 'Вършец          '),
(null, 'Габрово         '),
(null, 'Гевгели         '),
(null, 'Горна Оряховица '),
(null, 'Гоце Делчев     '),
(null, 'Гюмюрджина      '),
(null, 'Дедеагач        '),
(null, 'Демир Хисар     '),
(null, 'Димитровград    '),
(null, 'Добрич          '),
(null, 'Дойран          '),
(null, 'Долна Баня      '),
(null, 'Долна Оряховица '),
(null, 'Долни Дъбник    '),
(null, 'Драма           '),
(null, 'Дупница         '),
(null, 'Елена           '),
(null, 'Исперих         '),
(null, 'Ихтиман         '),
(null, 'Кавала          '),
(null, 'Каварна         '),
(null, 'Казанлък        '),
(null, 'Калофер         '),
(null, 'Карлово         '),
(null, 'Карнобат        '),
(null, 'Кешан           '),
(null, 'Китен           '),
(null, 'Козлодуй        '),
(null, 'Копривщица      '),
(null, 'Костенец        '),
(null, 'Костур          '),
(null, 'Котел           '),
(null, 'Кресна          '),
(null, 'Крушево         '),
(null, 'Ксанти          '),
(null, 'Кукуш           '),
(null, 'Кърджали        '),
(null, 'Кюстендил       '),
(null, 'Лерин           '),
(null, 'Ловеч           '),
(null, 'Лозенград       '),
(null, 'Лом             '),
(null, 'Люле Бургас     '),
(null, 'Мадан           '),
(null, 'Мелник          '),
(null, 'Момчилград      '),
(null, 'Монтана         '),
(null, 'Несебър         '),
(null, 'Никопол         '),
(null, 'Ниш             '),
(null, 'Нова Загора     '),
(null, 'Обзор           '),
(null, 'Одрин           '),
(null, 'Оряхово         '),
(null, 'Охрид           '),
(null, 'Павликени       '),
(null, 'Пазарджик       '),
(null, 'Панагюрище      '),
(null, 'Перник          '),
(null, 'Перущица        '),
(null, 'Петрич          '),
(null, 'Пещера          '),
(null, 'Пирдоп          '),
(null, 'Плевен          '),
(null, 'Пловдив         '),
(null, 'Поморие         '),
(null, 'Попово          '),
(null, 'Пордим          '),
(null, 'Правец          '),
(null, 'Прилеп          '),
(null, 'Приморско       '),
(null, 'Провадия        '),
(null, 'Първомай        '),
(null, 'Радомир         '),
(null, 'Разград         '),
(null, 'Разлог          '),
(null, 'Русе            '),
(null, 'Самоков         '),
(null, 'Сандански       '),
(null, 'Свиленград      '),
(null, 'Свищов          '),
(null, 'Своге           '),
(null, 'Севлиево        '),
(null, 'Серес           '),
(null, 'Силистра        '),
(null, 'Симеоновград    '),
(null, 'Скопие          '),
(null, 'Сливен          '),
(null, 'Смолян          '),
(null, 'Созопол         '),
(null, 'Солун           '),
(null, 'Сопот           '),
(null, 'София           '),
(null, 'Стара Загора    '),
(null, 'Стражица        '),
(null, 'Струга          '),
(null, 'Струмица        '),
(null, 'Тетово          '),
(null, 'Тополовград     '),
(null, 'Троян           '),
(null, 'Трън            '),
(null, 'Тулча           '),
(null, 'Тутракан        '),
(null, 'Търговище       '),
(null, 'Харманли        '),
(null, 'Хасково         '),
(null, 'Хисар           '),
(null, 'Царево          '),
(null, 'Цариброд        '),
(null, 'Цариград        '),
(null, 'Чаталджа        '),
(null, 'Чепеларе        '),
(null, 'Червен бряг     '),
(null, 'Чирпан          '),
(null, 'Чорлу           '),
(null, 'Шумен           '),
(null, 'Щип             '),
(null, 'Якоруда         '),
(null, 'Ямбол           ');

update cities set city_name = trim(city_name) where id > 0;

ALTER TABLE genders ADD CONSTRAINT gender_name_uq UNIQUE (gender_name);

insert into genders values (null, 'male');
insert into genders values (null, 'female');
insert into genders values (null, 'unspecified');
insert into genders values (null, 'this wont work');